spring:
  info:
    app:
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
  main:
    banner-mode: "off"

server:
  error.whitelabel.enabled: false
  shutdown: graceful

management:
  server:
    add-application-context-header: false
    port: 8090
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - metrics
          - info
          - health
          - prometheus

rest-client-config:
  http-bin:
    base-url: "http://localhost:8001/"
    paths:
      get: "/get"
      slide-show: "/json"

resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.HttpClientErrorException$TooManyRequests  # 429