spring:
  info:
    app:
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
  main:
    banner-mode: "off"
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: true
      write_dates_as_timestamps: false
    serialization-inclusion: non_null
  cache:
    cache-names: http-bin-cache
    caffeine:
      spec: expireAfterWrite=3s

server:
  error.whitelabel.enabled: false
  shutdown: graceful

management:
  server:
    add-application-context-header: false
    port: 8090
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - metrics
          - info
          - health
          - prometheus

services:
  http-bin:
    base-url: "http://localhost:8001"
    paths:
      get: "/get"
      post: "/post"
      put: "/put"

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - dev.coding.common.exception.system.rest.RestCallShouldRetryException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - dev.coding.common.exception.BusinessException
    instances:
      http-bin:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 10
        slidingWindowSize: 10         # if, over the last 10 requests
        failureRateThreshold: 50      # 50% of them fail
        waitDurationInOpenState: 1000 # then open the circuit and wait for 1 second.
        permittedNumberOfCallsInHalfOpenState: 1
        registerHealthIndicator: true
        recordExceptions:
          - dev.coding.common.exception.system.rest.RestCallShouldRetryException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - dev.coding.common.exception.BusinessException
    instances:
      http-bin:
        baseConfig: default
