spring:
  info:
    app:
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
  main:
    banner-mode: "off"

server:
  error.whitelabel.enabled: false
  shutdown: graceful

management:
  server:
    add-application-context-header: false
    port: 8090
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - metrics
          - info
          - health
          - prometheus

rest-client-config:
  http-bin:
    base-url: ${SERVICE_ENDPOINT_HTTP_BIN_SERVICE_BASE_URL:http://localhost:8001/}
    paths:
      get: "/get"
      slide-show: "/json"